name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Inject API Key into HTML
        run: |
          # Create a temporary file with the replacement
          sed 's|<script src="env.js"></script>|<script>const API_KEY = "${{ secrets.GEMINI_API_KEY }}";</script>|g' index.html > temp.html
          mv temp.html index.html
          
      - name: Verify injection
        run: |
          echo "Directory contents:"
          ls -la
          echo "Checking if API_KEY placeholder exists in HTML:"
          grep "API_KEY" index.html || echo "API_KEY not found in HTML"
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }} 