name: Pre-deployment cleanup

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Remove env.js from .gitignore for deployment
        run: |
          sed -i '/env.js/d' .gitignore
          cat .gitignore # Debug: verify the change 